name: PHPUnit

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sitecounter

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl, mbstring, sqlite3
          coverage: xdebug

      - name: Validate composer
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPUnit
        env:
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit
